name: Groovy Pipe

on:
  push:
    branches: [ '*' ]

  workflow_dispatch:


jobs:
  groovy:
    name: dotnet test and build
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: ls
      run: ls
