name: Groovy Pipe

on:
  push:
    paths: [ SharedLibrary.Jenkins/** ]
    branches: [ '*' ]

  workflow_dispatch:


jobs:
  groovy:
    name: Groovy Tests
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4

    - name: Install OpenJDK
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jre
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_ENV

    - name: Install Groovy
      run: |
        sudo apt install -y zip unzip
        wget https://www.apache.org/dyn/closer.lua/groovy/4.0.9/distribution/apache-groovy-binary-4.0.9.zip?action=download -O groovy.zip
        unzip groovy.zip -d /opt
        echo "PATH=$PATH:/opt/groovy-4.0.9/bin" >> $GITHUB_ENV
        rm -rf groovy.zip

    - name: Install SQLite JDBC Driver
      run: wget https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.47.0.0/sqlite-jdbc-3.47.0.0.jar -O /opt/sqlite-jdbc.jar

    - name: Install Spock and SLF4J Dependencies
      run: |
        wget https://repo1.maven.org/maven2/org/spockframework/spock-core/2.3-groovy-4.0/spock-core-2.3-groovy-4.0.jar -O /opt/spock-core.jar
        wget https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/2.0.9/slf4j-simple-2.0.9.jar -O /opt/slf4j-simple.jar

    - name: Set CLASSPATH for Groovy Tests
      run: echo "CLASSPATH=/opt/sqlite-jdbc.jar:/opt/spock-core.jar:/opt/slf4j-simple.jar" >> $GITHUB_ENV

    - name: Verify Environment Setup
      run: |
        java -version
        groovy -version

    - name: Run Test
      run: |
        groovy SharedLibrary.Jenkins/Tests/SqlLiteInMemoryTests.groovy  
